# Compiler settings
CC=gcc
CFLAGS=-Wall -Wextra -pedantic -g


# Program structure
INC=./inc
SRC=./src
BLD=./build

# BEGIN: Generated by ChatGPT
SRCS := $(wildcard $(SRC)/*.c)
OBJS := $(patsubst $(SRC)/%.c, $(BLD)/%.o, $(SRCS))
# END: Generated by ChatGPT


# OS checking
ifeq ($(OS),Windows_NT)
	EXE := $(BLD)/dis-psx.exe
else
	EXE := $(BLD)/dis-psx
endif


# Code targets
all: $(EXE)

# BEGIN: Generated by ChatGPT
$(EXE): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^


$(BLD)/%.o: $(SRC)/%.c
	$(CC) $(CFLAGS) -c $< -o $@ -I$(INC)
# END: Generated by ChatGPT


# Utility targets
.PHONY: clean
clean:
	rm -rf $(BLD)/*


.PHONY: run
run:
	$(EXE)	
